# 01 - Exploração da Base de Dados

Este notebook tem como objetivo realizar a exploração inicial da base de dados fornecida pela CTI, compreendendo sua estrutura, características, tipos de dados, valores ausentes, duplicidades e possíveis inconsistências.
Ao longo de todo o notebook fizemos as seguintes etapas:
- Identificação da fonte
- Coleta de dados iniciais
- Descrição dos dados
- Exploração dos dados
- Seleção de dados
- Limpeza e uniformização dos dados
- Derivação e integração dos dados
- Formatação dos dados

Observação: indicamos com markdowns em negrito cada uma das etapas listadas acima.

IMPORTANDO BIBLIOTECA

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Identificação da fonte de dados**

**Fonte:** CTI                                          
**Arquivo:** Demonstrativo Fecap v3.csv  
**Formato:** CSV  
**Tipo de dado:** Dados financeiros projetados  
**Período:** Ano 1 ao Ano 12  
**Cenários:** 1.200  
**Contas financeiras:** 69   
**Granularidade:** Ano × Cenário × Conta x Valor

A base contém dados financeiros projetados organizados por ano, cenário e conta contábil e seu respectivo valor. Os cenários representam diferentes simulações da projeção financeira e serão utilizados para análises comparativas e construção de indicadores para o dashboard.

**Resumo sobre a exploração**
Utilizamos a base raw para analisar todo seu conteúdo, os códigos abaixo demonstram como chegamos aos resultados.

In [60]:
resumo_base = pd.DataFrame({
    "Informação": [
        "Quantidade de registros",
        "Quantidade de anos",
        "Quantidade de cenários",
        "Quantidade de contas financeiras",
        "Quantidade de colunas"
    ],
    "Valor": [
        len(df),
        df["Ano"].nunique(),
        df["Cenario"].nunique(),
        df["Conta"].nunique(),
        df.shape[1]
    ]
})

resumo_base

                         Informação    Valor
0           Quantidade de registros  1002000
1                Quantidade de anos       12
2            Quantidade de cenários     1200
3  Quantidade de contas financeiras       69
4             Quantidade de colunas        4

**Descrição dos dados**

A base é composta por quatro campos principais:

Ano: Identifica o período da projeção financeira, do Ano 1 ao Ano 12. 
Cenario: Identifica cada cenário da simulação, totalizando 1.200 cenários. 
Conta: Identifica a conta associada ao registro. 
Valor: Representa o valor financeiro associado à conta, cenário e ano. 

A base possui 1.002.000 registros e apresenta dados financeiros organizados pela combinação entre ano, cenário e conta.

IMPORTANDO BASE

In [61]:
caminho = "../data/raw/Demonstrativo Fecap v3.csv"
df_amostra = pd.read_csv(caminho, sep=";", encoding="latin-1", nrows=1000) #df_amostra é uma amostra da base de dados, para não carregar toda a base de dados, que é muito grande
df_amostra.head() #.head mostra as primeiras linhas 
df_amostra.columns # mostra todas s colunas que tem na base de dados

Index(['Ano 1', 'Total Cen_00001', 'Unnamed: 2', '0,025138815'], dtype='str')

**Coleta dos dados iniciais**

A base de dados foi disponibilizada em formato CSV e explorada utilizando a biblioteca Pandas.

O arquivo foi importado diretamente da pasta `data/raw`, preservando os dados originais para garantir a rastreabilidade e permitir que as etapas de tratamento sejam realizadas posteriormente.

In [62]:
df = pd.read_csv(
    caminho,
    sep=";",
    encoding="latin-1",
    header=None,
    names=["Ano", "Cenario", "Conta", "Valor"]
)

**Seleção dos dados**

Para as análises financeiras e construção do dashboard, foram selecionadas contas dos demonstrativos de Balanço Patrimonial (BAL), Demonstração do Resultado do Exercício (DRE) e Fluxo de Caixa (FLU).

Balanço Patrimonial (BAL)
- BAL - Ativo Circulante
- BAL - Disponível
- BAL - Estoques Diversos
- BAL - Realizável a Longo Prazo
- BAL - Passivo Circulante
- BAL - Exigível a Longo Prazo
- BAL - Patrimônio Líquido
- BAL - Permanente
- BAL - Emprést
- BAL - Empréstimos

Demonstração do Resultado do Exercício 
- DRE - Receita
- DRE - Tributos
- DRE - Custos
- DRE - Resultado Operacional
- DRE - Resultado Antes do Imposto de Renda
- DRE - Imposto de Renda e Contribuição Social
- DRE - Resultado Líquido
- DRE - Receitas Financeiras
- DRE - Despesas Financeiras
- DRE - EBITDA

Fluxo de Caixa (FLU)
- FLU - Geração de Caixa
- FLU - Investimentos
- FLU - Saldo Inicial
- FLU - Saldo Final

A seleção foi realizada considerando a relevância das contas para a análise financeira, comparação entre cenários, acompanhamento da evolução ao longo dos anos e construção dos indicadores do dashboard.

In [63]:
df_amostra.head(10).T

,0,1,2,3,4,5,6,7,8,9
Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1
Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001
Unnamed: 2,BAL - Total do Ativo,BAL - Ativo Circulante,BAL - Disponível,BAL - Contas a Receber - SWAP,BAL - Contas a Receber - Partes Relacionadas,BAL - Contas a Receber - Clientes,BAL - Estoques Diversos,BAL - Outros Créditos,BAL - Realizável a Longo Prazo,BAL - At Fiscal Diferido
"0,025138815","10.631.127.075,26","1.795.720.872,18","1.205.264.965,52","95.680.421,92","584.661,47","453.870.957,15","86.620,79","40.233.245,33","639.023.858,23","-103.969.289,50"

In [64]:
df_amostra = pd.read_csv( #usando amostra para não carregar toda a base de dados, que é muito grande
    caminho,
    sep=";",
    encoding="latin-1",
    header=2, # a linha 2 é o onde esta o nome das variaveis, então o pandas vai ler a partir dela
    nrows=1000
)

df_amostra.head()

,Ano 1,Total Cen_00001,BAL - Ativo Circulante,"1.795.720.872,18"
0,Ano 1,Total Cen_00001,BAL - Disponível,"1.205.264.965,52"
1,Ano 1,Total Cen_00001,BAL - Contas a Receber - SWAP,"95.680.421,92"
2,Ano 1,Total Cen_00001,BAL - Contas a Receber - Partes Relacionadas,"584.661,47"
3,Ano 1,Total Cen_00001,BAL - Contas a Receber - Clientes,"453.870.957,15"
4,Ano 1,Total Cen_00001,BAL - Estoques Diversos,"86.620,79"

QUANTIDADE TOTAL DE LINHAS DA BASE/DE REGISTROS NA BASE

In [65]:
print("Quantidade total de linhas:", len(df))

Quantidade total de linhas: 1002000

QUANTIDADE DE REGISTROS POR CENÁRIO

In [66]:
df.groupby("Cenario").size().value_counts() #linhas por cenário, e quantos cenários tem com essa quantidade de linhas

835    1200
Name: count, dtype: int64

QUANTIDADE DE REGISTROS POR ANO

In [67]:
df.groupby("Ano").size()
#resultado: ano 12 tem menos linhas

Ano
Ano 1     85200
Ano 10    86400
Ano 11    86400
Ano 12    54000
Ano 2     85200
Ano 3     86400
Ano 4     86400
Ano 5     86400
Ano 6     86400
Ano 7     86400
Ano 8     86400
Ano 9     86400
dtype: int64

CENÁRIOS POR ANO

In [68]:
df.groupby("Ano")["Cenario"].nunique()
#resultado: 1200 cenários diferentes para cada ano

Ano
Ano 1     1200
Ano 10    1200
Ano 11    1200
Ano 12    1200
Ano 2     1200
Ano 3     1200
Ano 4     1200
Ano 5     1200
Ano 6     1200
Ano 7     1200
Ano 8     1200
Ano 9     1200
Name: Cenario, dtype: int64

QUANTAS LINHAS CADA CENÁRIO TEM DENTRO DE CADA ANO

In [69]:
df.groupby(["Ano", "Cenario"]).size() \
  .groupby(level=0) \
  .value_counts() \
  .rename_axis(["Ano", "Linhas por cenário"]) \
  .reset_index(name="Quantidade de cenários")

       Ano  Linhas por cenário  Quantidade de cenários
0    Ano 1                  71                    1200
1   Ano 10                  72                    1200
2   Ano 11                  72                    1200
3   Ano 12                  45                    1200
4    Ano 2                  71                    1200
5    Ano 3                  72                    1200
6    Ano 4                  72                    1200
7    Ano 5                  72                    1200
8    Ano 6                  72                    1200
9    Ano 7                  72                    1200
10   Ano 8                  72                    1200
11   Ano 9                  72                    1200

BASE COM CABEÇALHO: ANO | CENARIO | CONTA | VALOR                                             
QUANTIDADE DE COLUNAS

In [70]:
df_amostra = pd.read_csv(
    caminho,
    sep=";",
    encoding="latin-1",
    header=None,
    names=["Ano", "Cenario", "Conta", "Valor"], #mostra as as colunas que tem na base de dados
    nrows=1000
)

df_amostra.head(10)

,Ano,Cenario,Conta,Valor
0,Ano 1,Total Cen_00001,NaN,"0,025138815"
1,Ano 1,Total Cen_00001,BAL - Total do Ativo,"10.631.127.075,26"
2,Ano 1,Total Cen_00001,BAL - Ativo Circulante,"1.795.720.872,18"
3,Ano 1,Total Cen_00001,BAL - Disponível,"1.205.264.965,52"
4,Ano 1,Total Cen_00001,BAL - Contas a Receber - SWAP,"95.680.421,92"
5,Ano 1,Total Cen_00001,BAL - Contas a Receber - Partes Relacionadas,"584.661,47"
6,Ano 1,Total Cen_00001,BAL - Contas a Receber - Clientes,"453.870.957,15"
7,Ano 1,Total Cen_00001,BAL - Estoques Diversos,"86.620,79"
8,Ano 1,Total Cen_00001,BAL - Outros Créditos,"40.233.245,33"
9,Ano 1,Total Cen_00001,BAL - Realizável a Longo Prazo,"639.023.858,23"

In [71]:
df_amostra.info() #mostra informações sobre a base de dados, como o tipo de cada coluna e se tem valores nulos
#resultado: temos 1000 linhas e 4 colunas, sendo que a coluna Valor é do tipo float64, e as colunas Ano, Cenario e Conta são do tipo object. A coluna Valor tem 43 valores nulos, o que representa 4,3% dos dados. As outras colunas não tem valores nulos.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ano      1000 non-null   str
 1   Cenario  1000 non-null   str
 2   Conta    957 non-null    str
 3   Valor    1000 non-null   str
dtypes: str(4)
memory usage: 31.4 KB

In [72]:
df_amostra["Cenario"].unique() #mostra os cenários que tem na base de dados nas primeiras 1000 linhas
# resultado: dentro das primeiras 1000 linhas, temos 1 ano, 15 cenarios

<StringArray>
['Total Cen_00001', 'Total Cen_00002', 'Total Cen_00003', 'Total Cen_00004',
 'Total Cen_00005', 'Total Cen_00006', 'Total Cen_00007', 'Total Cen_00008',
 'Total Cen_00009', 'Total Cen_00010', 'Total Cen_00011', 'Total Cen_00012',
 'Total Cen_00013', 'Total Cen_00014', 'Total Cen_00015']
Length: 15, dtype: str

In [73]:
df_amostra["Cenario"].value_counts() #mostra a quantidade de vezes que cada cenário aparece na base de dados nas primeiras 1000 linhas
# resultado: no cenario 00001, tem 71 registros, no cenario 00002, tem 71 registros, e assim por diante. O cenario 00015 tem 70 registros, que so mostrou parcialmente aqui. Isso mostra que a base de dados está balanceada, ou seja, cada cenário tem aproximadamente o mesmo número de registros.

Cenario
Total Cen_00001    71
Total Cen_00002    71
Total Cen_00003    71
Total Cen_00004    71
Total Cen_00005    71
Total Cen_00006    71
Total Cen_00007    71
Total Cen_00008    71
Total Cen_00009    71
Total Cen_00010    71
Total Cen_00011    71
Total Cen_00012    71
Total Cen_00013    71
Total Cen_00014    71
Total Cen_00015     6
Name: count, dtype: int64

In [74]:
df_amostra[df_amostra["Cenario"] == "Total Cen_00001"]["Conta"].unique() #descobrindo quais contas aparecem dentro de uma cenário específico, no caso o cenario 00001. O resultado mostra que dentro do cenario 00001, temos 71 contas diferentes, que são as mesmas contas que aparecem nos outros cenarios, então a base de dados está balanceada.
#resultado: temos 71 contas diferentes, que são as mesmas contas que aparecem nos outros cenarios, então a base de dados está balanceada.

<StringArray>
[                                           nan,
                         'BAL - Total do Ativo',
                       'BAL - Ativo Circulante',
                             'BAL - Disponível',
                'BAL - Contas a Receber - SWAP',
 'BAL - Contas a Receber - Partes Relacionadas',
            'BAL - Contas a Receber - Clientes',
                      'BAL - Estoques Diversos',
                        'BAL - Outros Créditos',
               'BAL - Realizável a Longo Prazo',
                     'BAL - At Fiscal Diferido',
                   'BAL - Créditos Tributários',
                   'BAL - Outorga da Concessão',
                     'BAL - Outros Créditos LP',
                             'BAL - Permanente',
            'BAL - Investimentos - Imobilizado',
             'BAL - Investimentos - Intangível',
                               'BAL - Diferido',
                  'BAL - Depreciação Acumulada',
                  'BAL - Amortização Acumulada',
               'BAL - Amortização - Intangível',
                       'BAL - Total do Passivo',
                     'BAL - Passivo Circulante',
                            'BAL - Empréstimos',
     'BAL - Contas a Pagar - Parte Relacionada',
                           'BAL - Fornecedores',
        'BAL - Encargos Sociais e Trabalhistas',
                       'BAL - Tributos a pagar',
                               'BAL - Impostos',
      'BAL - Obrigações com o Poder Concedente',
                         'BAL - Outros Débitos',
                    'BAL - Provisão Manutenção',
                 'BAL - Exigível a Longo Prazo',
                                'BAL - Emprést',
               'BAL  - Prov para Contingências',
                             'BAL - Outros deb',
                    'BAL  - Patrimônio Líquido',
                        'BAL  - Capital Social',
                   'BAL  - Reservas de Capital',
                       'BAL  - Reservas Legais',
         'BAL  - Reserva de Retenção de Lucros',
                   'BAL  - Resultado Acumulado',
                  'BAL  - Resultado do Período',
                                'DRE - Receita',
                               'DRE - Tributos',
                                 'DRE - Custos',
              'DRE - Depreciação e Amortização',
                  'DRE - Resultado Operacional',
                   'DRE - Receitas Financeiras',
                   'DRE - Despesas Financeiras',
                   'DRE - Resultado Financeiro',
         'DRE - Outros Resultados Operacionais',
    'DRE - Resultado Antes do Imposto de Renda',
 'DRE - Imposto de Renda e Contribuição Social',
                      'DRE - Resultado Líquido',
    'DRE - Resultado Líquido após Equivalência',
                                 'DRE - EBITDA',
                          'FLU - Saldo Inicial',
                                'FLU - Receita',
                               'FLU - Tributos',
                                 'FLU - Custos',
                          'FLU - Investimentos',
                               'FLU - Entradas',
                   'FLU - Despesas Financeiras',
                   'FLU - Resultado Financeiro',
 'FLU - Imposto de Renda e Contribuição Social',
            'FLU - Distribuição para Acionista',
                       'FLU - Geração de Caixa',
                            'FLU - Saldo Final']
Length: 69, dtype: str

QUANTIDADE DE REGISTROS POR CONTA: BAL,DRE E FLU

In [75]:
df_amostra["Conta"].dropna().str[:3].value_counts() #mostra a quantidade de vezes que cada conta aparece na base de dados nas primeiras 1000 linhas, considerando apenas os 3 primeiros caracteres da conta, que são os que indicam o tipo de conta. 
#df_amostra["Conta"] mostra só a coluna Conta
#.dropna() remove os valores nulos
#.str[:3] pega os 3 primeiros caracteres da conta

# O resultado mostra que temos 4 tipos de contas diferentes: 1. Receitas, 2. Custos, 3. Despesas e 4. Resultado.
# no info () vimos 957 valores preenchidos em conta, entao bateu. ou seja, temos 69 contas diferentes que aparece varias vezes uma vez em cada cenario

Conta
BAL    593
DRE    196
FLU    168
Name: count, dtype: int64

In [76]:
df_amostra[df_amostra["Cenario"] == "Total Cen_00001"].isna().sum() #diz quantos valores vazios tem em cada coluna de um cenario completo
#resultado, no cenario 00001, temos 0 valores nulos em Ano, Cenario e Conta, e 3 valores nulos em Valor. Isso mostra que a base de dados está balanceada, ou seja, cada cenário tem aproximadamente o mesmo número de registros.
df_amostra[
    (df_amostra["Cenario"] == "Total Cen_00001") &
    (df_amostra["Conta"].isna())
] #mostra os registros onde a conta é nula no cenario 00001
df_amostra["Cenario"].value_counts()

Cenario
Total Cen_00001    71
Total Cen_00002    71
Total Cen_00003    71
Total Cen_00004    71
Total Cen_00005    71
Total Cen_00006    71
Total Cen_00007    71
Total Cen_00008    71
Total Cen_00009    71
Total Cen_00010    71
Total Cen_00011    71
Total Cen_00012    71
Total Cen_00013    71
Total Cen_00014    71
Total Cen_00015     6
Name: count, dtype: int64

ESTRUTURA DAS CONTAS

In [77]:
df_amostra[
    (df_amostra["Cenario"] == "Total Cen_00001") &
    (df_amostra["Conta"].notna())
]["Conta"].str[:3].value_counts()

Conta
BAL    42
DRE    14
FLU    12
Name: count, dtype: int64

In [78]:
df_amostra[
    df_amostra["Cenario"] == "Total Cen_00002"
]["Conta"].dropna().nunique()
#temos 71 registros por cenario, 69 contas e 3 parametros separando BAL, DRE e FLU

68

In [79]:
contas_cenario_1 = set(
    df_amostra[
        df_amostra["Cenario"] == "Total Cen_00001"
    ]["Conta"].dropna()
) #nao aparece nada, é so pra guardar essa estrutura como amostra, para depois comparar com os outros cenarios e ver se tem alguma conta que aparece em um cenario e não aparece em outro

QUANTIDADE DE ANOS E CENÁRIOS NO TOTAL

In [82]:
df = pd.read_csv( #lendo a base inteira, que tem 1.071.000 linhas e 4 colunas, e salvando em um dataframe chamado df
    caminho,
    sep=";",
    encoding="latin-1",
    header=None,
    names=["Ano", "Cenario", "Conta", "Valor"]
)

print("Quantidade total de anos:", df["Ano"].nunique()) #quantos anos diferentes tem na base de dados
print("Quantidade total de cenários:", df["Cenario"].nunique()) #quantos cenários diferentes tem na base de dados

Quantidade total de anos: 12
Quantidade total de cenários: 1200

VALORES AUSENTES NAS COLUNAS

In [83]:
df.isna().sum() #verifica celula por celula se tem algum valor nulo, e mostra a quantidade de valores nulos em cada coluna.
#resultado :43.000 valores nulos em conta
#a coluna Conta tem valores ausentes, ou seja 4, 31%
#são valores nulos pq tem 3600 campos nulos em conta em cada ano (1 ao 12) devido serem 71 linhas para cada cenario e 3 serem paramentros para dividir, ou seja 68 contas

Ano            0
Cenario        0
Conta      43200
Valor          0
dtype: int64

DUPLICIDADE

In [84]:
df.duplicated().sum() #verifica se tem linha duplicada
#resultado: 14400 linhas duplicadas
df[df.duplicated()].groupby("Ano").size()
#1200 duplicidades para cada ano, ou seja, não sao aleatorias
df[df.duplicated()][["Ano", "Cenario", "Conta", "Valor"]].head(20)
#resultado: as duplicidades são por conta das linhas de Total por cenario

        Ano          Cenario Conta Valor
58    Ano 1  Total Cen_00001   NaN     0
129   Ano 1  Total Cen_00002   NaN     0
200   Ano 1  Total Cen_00003   NaN     0
271   Ano 1  Total Cen_00004   NaN     0
342   Ano 1  Total Cen_00005   NaN     0
413   Ano 1  Total Cen_00006   NaN     0
484   Ano 1  Total Cen_00007   NaN     0
555   Ano 1  Total Cen_00008   NaN     0
626   Ano 1  Total Cen_00009   NaN     0
697   Ano 1  Total Cen_00010   NaN     0
768   Ano 1  Total Cen_00011   NaN     0
839   Ano 1  Total Cen_00012   NaN     0
910   Ano 1  Total Cen_00013   NaN     0
981   Ano 1  Total Cen_00014   NaN     0
1052  Ano 1  Total Cen_00015   NaN     0
1123  Ano 1  Total Cen_00016   NaN     0
1194  Ano 1  Total Cen_00017   NaN     0
1265  Ano 1  Total Cen_00018   NaN     0
1336  Ano 1  Total Cen_00019   NaN     0
1407  Ano 1  Total Cen_00020   NaN     0

In [85]:
df[df.duplicated()][["Ano", "Cenario", "Conta", "Valor"]].groupby(
    ["Ano", "Conta", "Valor"]
).size().reset_index(name="Quantidade") #estrutura ano | cenario | conta | valor e ao lado quantidade de vezes que essa combinação aparece
df[df["Cenario"] == "Total Cen_00001"].isna().sum() # verificando se alem da linha de total tem outras duplicadas, resultado: tem
df[
    (df["Cenario"] == "Total Cen_00001") &
    (df["Conta"].isna())
][["Ano", "Cenario", "Conta", "Valor"]]
df[
    df.duplicated(
        subset=["Ano", "Cenario", "Conta"],
        keep=False
    )
][["Ano", "Cenario", "Conta", "Valor"]].head(20)

       Ano          Cenario Conta        Valor
0    Ano 1  Total Cen_00001   NaN  0,025138815
43   Ano 1  Total Cen_00001   NaN            0
58   Ano 1  Total Cen_00001   NaN            0
71   Ano 1  Total Cen_00002   NaN  0,025138809
114  Ano 1  Total Cen_00002   NaN            0
129  Ano 1  Total Cen_00002   NaN            0
142  Ano 1  Total Cen_00003   NaN  0,025138818
185  Ano 1  Total Cen_00003   NaN            0
200  Ano 1  Total Cen_00003   NaN            0
213  Ano 1  Total Cen_00004   NaN   0,02513882
256  Ano 1  Total Cen_00004   NaN            0
271  Ano 1  Total Cen_00004   NaN            0
284  Ano 1  Total Cen_00005   NaN  0,025138815
327  Ano 1  Total Cen_00005   NaN            0
342  Ano 1  Total Cen_00005   NaN            0
355  Ano 1  Total Cen_00006   NaN  0,025138816
398  Ano 1  Total Cen_00006   NaN            0
413  Ano 1  Total Cen_00006   NaN            0
426  Ano 1  Total Cen_00007   NaN   0,02513882
469  Ano 1  Total Cen_00007   NaN            0

**LIMPANDO E UNIFORMIZANDO DADOS**

In [86]:
contas_selecionadas = [
    "BAL - Ativo Circulante",
    "BAL - Disponível",
    "BAL - Estoques Diversos",
    "BAL - Realizável a Longo Prazo",
    "BAL - Passivo Circulante",
    "BAL - Exigível a Longo Prazo",
    "BAL - Patrimônio Líquido",
    "BAL - Permanente",
    "BAL - Emprést",
    "BAL - Empréstimos",
    "DRE - Receita",
    "DRE - Tributos",
    "DRE - Custos",
    "DRE - Resultado Operacional",
    "DRE - Resultado Antes do Imposto de Renda",
    "DRE - Imposto de Renda e Contribuição Social",
    "DRE - Resultado Líquido",
    "DRE - Receitas Financeiras",
    "DRE - Despesas Financeiras",
    "DRE - EBITDA",
    "FLU - Geração de Caixa",
    "FLU - Investimentos",
    "FLU - Saldo Inicial",
    "FLU - Saldo Final"
]

contas_encontradas = (
    df[df["Conta"].isin(contas_selecionadas)]["Conta"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

pd.DataFrame({
    "Contas encontradas": contas_encontradas
})
#RESULTADO: varias contas nao apreceram porque possuem nome diferente, como por exemplo "BAL - Empréstimos" e "BAL - Emprést", que são a mesma conta, mas com nomes diferentes. Isso mostra que a base de dados não está totalmente padronizada,

                              Contas encontradas
0                         BAL - Ativo Circulante
1                               BAL - Disponível
2                                  BAL - Emprést
3                              BAL - Empréstimos
4                        BAL - Estoques Diversos
5                   BAL - Exigível a Longo Prazo
6                       BAL - Passivo Circulante
7                               BAL - Permanente
8                 BAL - Realizável a Longo Prazo
9                                   DRE - Custos
10                    DRE - Despesas Financeiras
11                                  DRE - EBITDA
12  DRE - Imposto de Renda e Contribuição Social
13                                 DRE - Receita
14                    DRE - Receitas Financeiras
15     DRE - Resultado Antes do Imposto de Renda
16                       DRE - Resultado Líquido
17                   DRE - Resultado Operacional
18                                DRE - Tributos
19                        FLU - Geração de Caixa
20                           FLU - Investimentos
21                             FLU - Saldo Final
22                           FLU - Saldo Inicial

In [87]:
df["Conta"] = (
    df["Conta"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)
#uniformizando os nomes das contas, removendo espaços extras e padronizando a formatação

In [88]:
df[
    df["Conta"].isin(contas_selecionadas)
]["Conta"].drop_duplicates().sort_values().reset_index(drop=True)
#as 24 contas apareceram padronizadas

0                           BAL - Ativo Circulante
1                                 BAL - Disponível
2                                    BAL - Emprést
3                                BAL - Empréstimos
4                          BAL - Estoques Diversos
5                     BAL - Exigível a Longo Prazo
6                         BAL - Passivo Circulante
7                         BAL - Patrimônio Líquido
8                                 BAL - Permanente
9                   BAL - Realizável a Longo Prazo
10                                    DRE - Custos
11                      DRE - Despesas Financeiras
12                                    DRE - EBITDA
13    DRE - Imposto de Renda e Contribuição Social
14                                   DRE - Receita
15                      DRE - Receitas Financeiras
16       DRE - Resultado Antes do Imposto de Renda
17                         DRE - Resultado Líquido
18                     DRE - Resultado Operacional
19                                  DRE - Tributos
20                          FLU - Geração de Caixa
21                             FLU - Investimentos
22                               FLU - Saldo Final
23                             FLU - Saldo Inicial
Name: Conta, dtype: str

BASE SOMENTE COM CONTAS QUE VÃO SER USADAS

In [89]:
df_selecionado = df[
    df["Conta"].isin(contas_selecionadas) #apenas as 24
].copy()

df_selecionado.head()

      Ano          Cenario                           Conta             Valor
2   Ano 1  Total Cen_00001          BAL - Ativo Circulante  1.795.720.872,18
3   Ano 1  Total Cen_00001                BAL - Disponível  1.205.264.965,52
7   Ano 1  Total Cen_00001         BAL - Estoques Diversos         86.620,79
9   Ano 1  Total Cen_00001  BAL - Realizável a Longo Prazo    639.023.858,23
14  Ano 1  Total Cen_00001                BAL - Permanente  8.196.382.344,85

TAMANHO DA NOVA BASE    
essa será a nova base que utilizaresmo para fazer as análises e transforma os indicadores

In [90]:
resumo_selecao = pd.DataFrame({
    "Informação": [
        "Registros na base selecionada",
        "Anos",
        "Cenários",
        "Contas selecionadas"
    ],
    "Quantidade": [
        len(df_selecionado),
        df_selecionado["Ano"].nunique(),
        df_selecionado["Cenario"].nunique(),
        df_selecionado["Conta"].nunique()
    ]
})

resumo_selecao
#resultado: esperava 345.600 registros, 12 anos, 1.200 cenários e 24 contas selecionadas MAS APARECERAM MENOS REGISTROS

                      Informação  Quantidade
0  Registros na base selecionada      340800
1                           Anos          12
2                       Cenários        1200
3            Contas selecionadas          24

VERIFICANDO PORQUE 340MIL REGISTROS E NÃO 345MIL

In [91]:
resumo_contas = (
    df_selecionado.groupby("Conta")
    .size()
    .reset_index(name="Quantidade de registros")
    .sort_values("Quantidade de registros")
)

resumo_contas
#RESULTADO: As quatro contas: BAL - EMPRÉST, BAL - ESTOQUES DIVERSOS, BAL - EXIGIVEL A LONGO PRAZO, BAL - PATRIMONIO LIQUIDO aparecem 13.200 vezes, em vez de 14.400:

                                           Conta  Quantidade de registros
2                                  BAL - Emprést                    13200
7                       BAL - Patrimônio Líquido                    13200
5                   BAL - Exigível a Longo Prazo                    13200
4                        BAL - Estoques Diversos                    13200
3                              BAL - Empréstimos                    14400
1                               BAL - Disponível                    14400
0                         BAL - Ativo Circulante                    14400
6                       BAL - Passivo Circulante                    14400
8                               BAL - Permanente                    14400
9                 BAL - Realizável a Longo Prazo                    14400
10                                  DRE - Custos                    14400
11                    DRE - Despesas Financeiras                    14400
12                                  DRE - EBITDA                    14400
13  DRE - Imposto de Renda e Contribuição Social                    14400
14                                 DRE - Receita                    14400
15                    DRE - Receitas Financeiras                    14400
16     DRE - Resultado Antes do Imposto de Renda                    14400
17                       DRE - Resultado Líquido                    14400
18                   DRE - Resultado Operacional                    14400
19                                DRE - Tributos                    14400
20                        FLU - Geração de Caixa                    14400
21                           FLU - Investimentos                    14400
22                             FLU - Saldo Final                    14400
23                           FLU - Saldo Inicial                    14400

In [92]:
contas_incompletas = [
    "BAL - Emprést",
    "BAL - Estoques Diversos",
    "BAL - Exigível a Longo Prazo",
    "BAL - Patrimônio Líquido"
]

df_selecionado[
    df_selecionado["Conta"].isin(contas_incompletas)
].groupby(["Conta", "Ano"]).size().reset_index(name="Quantidade")
#resultado: o ano 12não possui as 4 contas

                           Conta     Ano  Quantidade
0                  BAL - Emprést   Ano 1        1200
1                  BAL - Emprést  Ano 10        1200
2                  BAL - Emprést  Ano 11        1200
3                  BAL - Emprést   Ano 2        1200
4                  BAL - Emprést   Ano 3        1200
5                  BAL - Emprést   Ano 4        1200
6                  BAL - Emprést   Ano 5        1200
7                  BAL - Emprést   Ano 6        1200
8                  BAL - Emprést   Ano 7        1200
9                  BAL - Emprést   Ano 8        1200
10                 BAL - Emprést   Ano 9        1200
11       BAL - Estoques Diversos   Ano 1        1200
12       BAL - Estoques Diversos  Ano 10        1200
13       BAL - Estoques Diversos  Ano 11        1200
14       BAL - Estoques Diversos   Ano 2        1200
15       BAL - Estoques Diversos   Ano 3        1200
16       BAL - Estoques Diversos   Ano 4        1200
17       BAL - Estoques Diversos   Ano 5        1200
18       BAL - Estoques Diversos   Ano 6        1200
19       BAL - Estoques Diversos   Ano 7        1200
20       BAL - Estoques Diversos   Ano 8        1200
21       BAL - Estoques Diversos   Ano 9        1200
22  BAL - Exigível a Longo Prazo   Ano 1        1200
23  BAL - Exigível a Longo Prazo  Ano 10        1200
24  BAL - Exigível a Longo Prazo  Ano 11        1200
25  BAL - Exigível a Longo Prazo   Ano 2        1200
26  BAL - Exigível a Longo Prazo   Ano 3        1200
27  BAL - Exigível a Longo Prazo   Ano 4        1200
28  BAL - Exigível a Longo Prazo   Ano 5        1200
29  BAL - Exigível a Longo Prazo   Ano 6        1200
30  BAL - Exigível a Longo Prazo   Ano 7        1200
31  BAL - Exigível a Longo Prazo   Ano 8        1200
32  BAL - Exigível a Longo Prazo   Ano 9        1200
33      BAL - Patrimônio Líquido   Ano 1        1200
34      BAL - Patrimônio Líquido  Ano 10        1200
35      BAL - Patrimônio Líquido  Ano 11        1200
36      BAL - Patrimônio Líquido   Ano 2        1200
37      BAL - Patrimônio Líquido   Ano 3        1200
38      BAL - Patrimônio Líquido   Ano 4        1200
39      BAL - Patrimônio Líquido   Ano 5        1200
40      BAL - Patrimônio Líquido   Ano 6        1200
41      BAL - Patrimônio Líquido   Ano 7        1200
42      BAL - Patrimônio Líquido   Ano 8        1200
43      BAL - Patrimônio Líquido   Ano 9        1200

FORMATANDO STRINGS

In [93]:
df_selecionado.dtypes

Ano        str
Cenario    str
Conta      str
Valor      str
dtype: object

In [94]:
df_selecionado["Valor"] = (
    df_selecionado["Valor"]
    .str.replace(".", "", regex=False)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

In [95]:
df_selecionado.dtypes

Ano            str
Cenario        str
Conta          str
Valor      float64
dtype: object

NULOS NAS 24 CONTAS SELECIONADAS

In [96]:
df_selecionado.isna().sum()
#resultado: na base nova não temos nenhum valor nulo

Ano        0
Cenario    0
Conta      0
Valor      0
dtype: int64

VERIFICANDO VALORES NEGATIVOS

In [98]:
df_selecionado["Valor"].lt(0).sum() #quantos valores da coluna valor são negativos

np.int64(129150)

In [ ]:
negativos_por_conta = (
    df_selecionado[df_selecionado["Valor"] < 0]
    .groupby("Conta")
    .size()
    .reset_index(name="Quantidade de negativos")
    .sort_values("Quantidade de negativos", ascending=False)
) #mostra a quantidade de valores negativos por conta, ordenando do maior para o menor
#resultado: Os negativos estão concentrados principalmente em contas em que é esperado haver valores negativos, como: DRE - Custos, DRE - Tributos, DRE - Despesas Financeiras, DRE - Imposto de Renda e Contribuição Social, FLU - Investimentos
negativos_por_conta

                                           Conta  Quantidade de negativos
10  DRE - Imposto de Renda e Contribuição Social                    14400
9                     DRE - Despesas Financeiras                    14400
13                           FLU - Investimentos                    14400
11                                DRE - Tributos                    14400
8                                   DRE - Custos                    14400
4                   BAL - Exigível a Longo Prazo                    13200
2                                  BAL - Emprést                    13200
6                       BAL - Patrimônio Líquido                    13137
12                        FLU - Geração de Caixa                     6155
5                       BAL - Passivo Circulante                     5434
3                              BAL - Empréstimos                     4800
7                               BAL - Permanente                     1200
0                         BAL - Ativo Circulante                       22
1                               BAL - Disponível                        1
14                             FLU - Saldo Final                        1

**QUANTIDADE DE REGISTROS, MENOR VALOR, MAIOR VALOR, MÉDIA, MEDIANA, DESVIO E QUARTIS**

In [ ]:
df_selecionado["Valor"].describe()

count    3.408000e+05
mean     1.036959e+09
std      3.589688e+09
min     -8.886329e+09
25%     -6.287165e+08
50%      3.212818e+08
75%      2.966866e+09
max      1.458960e+10
Name: Valor, dtype: float64

In [ ]:
extremos = (
    df_selecionado
    .loc[
        df_selecionado["Valor"].isin([
            df_selecionado["Valor"].min(),
            df_selecionado["Valor"].max()
        ])
    ]
    [["Ano", "Cenario", "Conta", "Valor"]]
)

extremos #mostra quais anos tiveram os valores mais extremso: menor e maior e em qual cenário
#resultado: Menor: Ano 11, Cenário 01128, Patrimônio Líquido = -R$ 8,886 bilhões e Maior: Ano 12, Cenário 01128, Receita = R$ 14,590 bilhões
# os dois pertencem ao mesmo cenário, o Cen_01128. Isso pode indicar que esse cenário simplesmente representa uma projeção mais extrema.

           Ano          Cenario                     Conta         Valor
942780  Ano 11  Total Cen_01128  BAL - Patrimônio Líquido -8.886329e+09
998733  Ano 12  Total Cen_01128             DRE - Receita  1.458960e+10

QUANTIDADE DE ZEROS NO TOTAL

In [104]:
(df_selecionado["Valor"] == 0).sum() #valores iguais a 0

np.int64(2112)

QUANTIDADE DE ZEROS POR CONTA

In [ ]:
zeros_por_conta = (
    df_selecionado[df_selecionado["Valor"] == 0]
    .groupby("Conta")
    .size()
    .reset_index(name="Quantidade de zeros")
    .sort_values("Quantidade de zeros", ascending=False)
)

zeros_por_conta
#RESULTADO: 2112 valores iguais a 0 e todos em DRE - Receitas financeiras

                        Conta  Quantidade de zeros
0  DRE - Receitas Financeiras                 2112

DUPLICADAS

In [107]:
df_selecionado.duplicated().sum()
#RESULTADO: NAO TEMOS CONTAS DUPLICADAS

np.int64(0)

**Limpeza e uniformização dos dados**

A etapa de limpeza foi realizada sobre a base selecionada, considerando as características dos dados financeiros.

Inicialmente, foi realizada a padronização dos nomes das contas, removendo espaços em excesso. Também foi verificada a existência de valores ausentes, não sendo identificados valores nulos na base selecionada.

A coluna Valor, originalmente armazenada como texto no formato numérico brasileiro (str), foi convertida para o tipo float64, permitindo a realização de cálculos e análises estatísticas.

Foram identificados 129.150 valores negativos e 2.112 valores iguais a zero. Esses valores foram mantidos, pois podem representar situações financeiras válidas, como custos, despesas, investimentos e ausência de receitas financeiras.

Também foram identificados valores extremos, sendo o menor valor de aproximadamente -R$ 8,89 bilhões e o maior de aproximadamente R$ 14,59 bilhões. Esses valores foram mantidos nesta etapa, pois não foram considerados erros automaticamente e poderão ser avaliados posteriormente durante a análise dos dados.

Por fim, não foram encontradas duplicatas exatas na base selecionada.

Foi observado ainda que quatro contas — BAL - Emprést, BAL - Estoques Diversos, BAL - Exigível a Longo Prazo e BAL - Patrimônio Líquido — não apresentam registros no Ano 12. Essa ausência foi mantida, sem preenchimento artificial, para preservar as características originais da base.

**Derivação dos dados**

In [ ]:
df_selecionado.head() #tabela com ano, cenario, conta e valor

      Ano          Cenario                           Conta         Valor
2   Ano 1  Total Cen_00001          BAL - Ativo Circulante  1.795721e+09
3   Ano 1  Total Cen_00001                BAL - Disponível  1.205265e+09
7   Ano 1  Total Cen_00001         BAL - Estoques Diversos  8.662079e+04
9   Ano 1  Total Cen_00001  BAL - Realizável a Longo Prazo  6.390239e+08
14  Ano 1  Total Cen_00001                BAL - Permanente  8.196382e+09

ANO + CENÁRIO

In [112]:
df_integrado = df_selecionado.pivot_table(
    index=["Ano", "Cenario"], #ano e canario em uma linha só
    columns="Conta", #cada conta vira uma coluna
    values="Valor", #valor fica dentro das colunas de cada conta
    aggfunc="first"
).reset_index()
#obs: as contas que não existem no ano 12, vao aparecer como nulos

In [113]:
df_integrado.head()

Conta,Ano,Cenario,BAL - Ativo Circulante,BAL - Disponível,BAL - Emprést,BAL - Empréstimos,BAL - Estoques Diversos,BAL - Exigível a Longo Prazo,BAL - Passivo Circulante,BAL - Patrimônio Líquido,...,DRE - Receita,DRE - Receitas Financeiras,DRE - Resultado Antes do Imposto de Renda,DRE - Resultado Líquido,DRE - Resultado Operacional,DRE - Tributos,FLU - Geração de Caixa,FLU - Investimentos,FLU - Saldo Final,FLU - Saldo Inicial
0,Ano 1,Total Cen_00001,1.795721e+09,1.205265e+09,-5.649257e+09,-2.791024e+08,86620.79,-7.535764e+09,-1.080928e+09,-2.014435e+09,...,6.722729e+09,91626997.28,3.723265e+09,2.443243e+09,4.286529e+09,-4.714642e+08,4.306498e+08,-5.340012e+08,1.205265e+09,7.746152e+08
1,Ano 1,Total Cen_00002,1.789812e+09,1.198931e+09,-5.649257e+09,-2.787313e+08,86620.79,-7.535764e+09,-1.080396e+09,-2.007754e+09,...,6.703608e+09,94348147.04,3.713084e+09,2.436562e+09,4.271291e+09,-4.700294e+08,4.243157e+08,-5.322824e+08,1.198931e+09,7.746152e+08
2,Ano 1,Total Cen_00003,1.790756e+09,1.195792e+09,-5.649257e+09,-2.760873e+08,86620.79,-7.535764e+09,-1.081422e+09,-2.005982e+09,...,6.676361e+09,97371239.24,3.710384e+09,2.434790e+09,4.248932e+09,-4.679849e+08,4.211763e+08,-5.303729e+08,1.195792e+09,7.746152e+08
3,Ano 1,Total Cen_00004,1.791311e+09,1.196228e+09,-5.649257e+09,-2.756026e+08,86620.79,-7.535764e+09,-1.080945e+09,-2.006577e+09,...,6.672623e+09,98075471.97,3.711290e+09,2.435385e+09,4.246084e+09,-4.677044e+08,4.216127e+08,-5.299281e+08,1.196228e+09,7.746152e+08
4,Ano 1,Total Cen_00005,1.770574e+09,1.179899e+09,-5.649257e+09,-2.788652e+08,86620.79,-7.535764e+09,-1.078829e+09,-1.987201e+09,...,6.660653e+09,97592316.08,3.681763e+09,2.416009e+09,4.237569e+09,-4.668062e+08,4.052842e+08,-5.282197e+08,1.179899e+09,7.746152e+08

ANO | CENÁRIO | CONTAS

In [114]:
df_integrado.columns.name = None

df_integrado.head()

,Ano,Cenario,BAL - Ativo Circulante,BAL - Disponível,BAL - Emprést,BAL - Empréstimos,BAL - Estoques Diversos,BAL - Exigível a Longo Prazo,BAL - Passivo Circulante,BAL - Patrimônio Líquido,...,DRE - Receita,DRE - Receitas Financeiras,DRE - Resultado Antes do Imposto de Renda,DRE - Resultado Líquido,DRE - Resultado Operacional,DRE - Tributos,FLU - Geração de Caixa,FLU - Investimentos,FLU - Saldo Final,FLU - Saldo Inicial
0,Ano 1,Total Cen_00001,1.795721e+09,1.205265e+09,-5.649257e+09,-2.791024e+08,86620.79,-7.535764e+09,-1.080928e+09,-2.014435e+09,...,6.722729e+09,91626997.28,3.723265e+09,2.443243e+09,4.286529e+09,-4.714642e+08,4.306498e+08,-5.340012e+08,1.205265e+09,7.746152e+08
1,Ano 1,Total Cen_00002,1.789812e+09,1.198931e+09,-5.649257e+09,-2.787313e+08,86620.79,-7.535764e+09,-1.080396e+09,-2.007754e+09,...,6.703608e+09,94348147.04,3.713084e+09,2.436562e+09,4.271291e+09,-4.700294e+08,4.243157e+08,-5.322824e+08,1.198931e+09,7.746152e+08
2,Ano 1,Total Cen_00003,1.790756e+09,1.195792e+09,-5.649257e+09,-2.760873e+08,86620.79,-7.535764e+09,-1.081422e+09,-2.005982e+09,...,6.676361e+09,97371239.24,3.710384e+09,2.434790e+09,4.248932e+09,-4.679849e+08,4.211763e+08,-5.303729e+08,1.195792e+09,7.746152e+08
3,Ano 1,Total Cen_00004,1.791311e+09,1.196228e+09,-5.649257e+09,-2.756026e+08,86620.79,-7.535764e+09,-1.080945e+09,-2.006577e+09,...,6.672623e+09,98075471.97,3.711290e+09,2.435385e+09,4.246084e+09,-4.677044e+08,4.216127e+08,-5.299281e+08,1.196228e+09,7.746152e+08
4,Ano 1,Total Cen_00005,1.770574e+09,1.179899e+09,-5.649257e+09,-2.788652e+08,86620.79,-7.535764e+09,-1.078829e+09,-1.987201e+09,...,6.660653e+09,97592316.08,3.681763e+09,2.416009e+09,4.237569e+09,-4.668062e+08,4.052842e+08,-5.282197e+08,1.179899e+09,7.746152e+08

In [115]:
pd.DataFrame({
    "Informação": [
        "Linhas",
        "Colunas",
        "Colunas de contas"
    ],
    "Quantidade": [
        len(df_integrado),
        len(df_integrado.columns),
        len(df_integrado.columns) - 2
    ]
})

          Informação  Quantidade
0             Linhas       14400
1            Colunas          26
2  Colunas de contas          24

**MARGEM EBITDA**

In [117]:
df_integrado["Margem EBITDA"] = (
    df_integrado["DRE - EBITDA"] / df_integrado["DRE - Receita"]
) * 100 #conta da margem ebitda: Margem EBITDA = EBITDA ÷ Receita × 100

In [118]:
df_integrado[
    ["Ano", "Cenario", "DRE - Receita", "DRE - EBITDA", "Margem EBITDA"]
].head() #ano, cenario, receita, ebitda e margem ebitda

     Ano          Cenario  DRE - Receita  DRE - EBITDA  Margem EBITDA
0  Ano 1  Total Cen_00001   6.722729e+09  5.188381e+09      77.176701
1  Ano 1  Total Cen_00002   6.703608e+09  5.172388e+09      77.158271
2  Ano 1  Total Cen_00003   6.676361e+09  5.149189e+09      77.125684
3  Ano 1  Total Cen_00004   6.672623e+09  5.146146e+09      77.123276
4  Ano 1  Total Cen_00005   6.660653e+09  5.136879e+09      77.122755

**MARGEM LÍQUIDA**

In [120]:
df_integrado["Margem Líquida"] = (
    df_integrado["DRE - Resultado Líquido"] / df_integrado["DRE - Receita"]
) * 100 #usa Resultado Liquido - receita

In [ ]:
df_integrado[
    ["Ano", "Cenario", "DRE - Receita", "DRE - Resultado Líquido", "Margem Líquida"]
].head() #Receita, Resultado Líquido e Margem Líquida para os primeiros cenários.

,Ano,Cenario,DRE - Receita,DRE - Resultado Líquido,Margem Líquida
0,Ano 1,Total Cen_00001,6.722729e+09,2.443243e+09,36.343022
1,Ano 1,Total Cen_00002,6.703608e+09,2.436562e+09,36.347021
2,Ano 1,Total Cen_00003,6.676361e+09,2.434790e+09,36.468819
3,Ano 1,Total Cen_00004,6.672623e+09,2.435385e+09,36.498164
4,Ano 1,Total Cen_00005,6.660653e+09,2.416009e+09,36.272850

**CAPITAL DE GIRO**

In [123]:
df_integrado["Capital de Giro"] = (
    df_integrado["BAL - Ativo Circulante"]
    - df_integrado["BAL - Passivo Circulante"]
) # conta do capital: Ativo Circulante − Passivo Circulante.

In [125]:
df_integrado[
    [
        "Ano",
        "Cenario",
        "BAL - Ativo Circulante",
        "BAL - Passivo Circulante",
        "Capital de Giro"
    ]
].head() #verificanod se a conta deu certo nos primeiros cenarios

,Ano,Cenario,BAL - Ativo Circulante,BAL - Passivo Circulante,Capital de Giro
0,Ano 1,Total Cen_00001,1.795721e+09,-1.080928e+09,2.876649e+09
1,Ano 1,Total Cen_00002,1.789812e+09,-1.080396e+09,2.870208e+09
2,Ano 1,Total Cen_00003,1.790756e+09,-1.081422e+09,2.872178e+09
3,Ano 1,Total Cen_00004,1.791311e+09,-1.080945e+09,2.872257e+09
4,Ano 1,Total Cen_00005,1.770574e+09,-1.078829e+09,2.849403e+09

**Derivação e integração dos dados**

Após a seleção e limpeza dos dados, a base foi reorganizada para facilitar as análises financeiras. Os dados foram transformados do formato longo para um formato analítico, no qual cada combinação de Ano e Cenario representa uma linha e as contas financeiras selecionadas passam a ser colunas.

A partir das contas disponíveis, foram derivados três indicadores financeiros:

- **Margem EBITDA:** calculada pela razão entre EBITDA e Receita, multiplicada por 100.
- **Margem Líquida:** calculada pela razão entre Resultado Líquido e Receita, multiplicada por 100.
- **Capital de Giro:** calculado pela diferença entre Ativo Circulante e Passivo Circulante.

Ao final dessa etapa, a base integrada possui **14.400 registros e 29 colunas**, sendo 24 contas financeiras, 2 campos de identificação (Ano e Cenario) e 3 indicadores derivados.

**Formatação dos dados**

In [130]:
df_integrado.columns = (
    df_integrado.columns
    .str.replace("___", "_", regex=False)
) #transforma, por exemplo: DRE - Receita → DRE___Receita, Margem EBITDA → Margem_EBITDA

NOME DAS COLUNAS

In [ ]:
df_integrado.columns.tolist() #temos: ano, cenario, 24 contas, Margem_EBITDA, Margem_Liquida e Capital_de_Giro. Totalizando 29 colunas.

['Ano',
 'Cenario',
 'BAL_Ativo_Circulante',
 'BAL_Disponível',
 'BAL_Emprést',
 'BAL_Empréstimos',
 'BAL_Estoques_Diversos',
 'BAL_Exigível_a_Longo_Prazo',
 'BAL_Passivo_Circulante',
 'BAL_Patrimônio_Líquido',
 'BAL_Permanente',
 'BAL_Realizável_a_Longo_Prazo',
 'DRE_Custos',
 'DRE_Despesas_Financeiras',
 'DRE_EBITDA',
 'DRE_Imposto_de_Renda_e_Contribuição_Social',
 'DRE_Receita',
 'DRE_Receitas_Financeiras',
 'DRE_Resultado_Antes_do_Imposto_de_Renda',
 'DRE_Resultado_Líquido',
 'DRE_Resultado_Operacional',
 'DRE_Tributos',
 'FLU_Geração_de_Caixa',
 'FLU_Investimentos',
 'FLU_Saldo_Final',
 'FLU_Saldo_Inicial',
 'Margem_EBITDA',
 'Margem_Líquida',
 'Capital_de_Giro']

In [132]:
df_integrado.info()

<class 'pandas.DataFrame'>
RangeIndex: 14400 entries, 0 to 14399
Data columns (total 29 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Ano                                         14400 non-null  str
 1   Cenario                                     14400 non-null  str
 2   BAL_Ativo_Circulante                        14400 non-null  float64
 3   BAL_Disponível                              14400 non-null  float64
 4   BAL_Emprést                                 13200 non-null  float64
 5   BAL_Empréstimos                             14400 non-null  float64
 6   BAL_Estoques_Diversos                       13200 non-null  float64
 7   BAL_Exigível_a_Longo_Prazo                  13200 non-null  float64
 8   BAL_Passivo_Circulante                      14400 non-null  float64
 9   BAL_Patrimônio_Líquido                      13200 non-null  float64
 10  BAL_Permanente                              14400 non-null  float64
 11  BAL_Realizável_a_Longo_Prazo                14400 non-null  float64
 12  DRE_Custos                                  14400 non-null  float64
 13  DRE_Despesas_Financeiras                    14400 non-null  float64
 14  DRE_EBITDA                                  14400 non-null  float64
 15  DRE_Imposto_de_Renda_e_Contribuição_Social  14400 non-null  float64
 16  DRE_Receita                                 14400 non-null  float64
 17  DRE_Receitas_Financeiras                    14400 non-null  float64
 18  DRE_Resultado_Antes_do_Imposto_de_Renda     14400 non-null  float64
 19  DRE_Resultado_Líquido                       14400 non-null  float64
 20  DRE_Resultado_Operacional                   14400 non-null  float64
 21  DRE_Tributos                                14400 non-null  float64
 22  FLU_Geração_de_Caixa                        14400 non-null  float64
 23  FLU_Investimentos                           14400 non-null  float64
 24  FLU_Saldo_Final                             14400 non-null  float64
 25  FLU_Saldo_Inicial                           14400 non-null  float64
 26  Margem_EBITDA                               14400 non-null  float64
 27  Margem_Líquida                              14400 non-null  float64
 28  Capital_de_Giro                             14400 non-null  float64
dtypes: float64(27), str(2)
memory usage: 3.2 MB

**Formatação dos dados**

Após a integração e derivação dos dados, a base foi formatada para facilitar sua utilização nas etapas de análise e construção do dashboard.

Os nomes das colunas foram padronizados, substituindo espaços e caracteres de separação por `_`, tornando os campos mais adequados para utilização em Python e ferramentas de visualização.

A base final apresenta **14.400 registros e 29 colunas**, sendo 2 colunas de identificação (Ano e Cenario), 24 contas financeiras selecionadas e 3 indicadores derivados: Margem_EBITDA, Margem_Líquida e Capital_de_Giro.

As colunas financeiras e os indicadores foram mantidos em formato numérico (float64), enquanto Ano e Cenario permanecem como texto. As ausências estruturais identificadas anteriormente foram preservadas, sem preenchimento artificial de valores.