# 01 - Exploração da Base de Dados

Este notebook tem como objetivo realizar a exploração inicial da base de dados fornecida pela CTI, compreendendo sua estrutura, características, tipos de dados, valores ausentes, duplicidades e possíveis inconsistências.

IMPORTANDO BIBLIOTECA

In [231]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

IMPORTANDO BASE

In [232]:
caminho = "../data/raw/Demonstrativo Fecap v3.csv"
df_amostra = pd.read_csv(caminho, sep=";", encoding="latin-1", nrows=1000) #df_amostra é uma amostra da base de dados, para não carregar toda a base de dados, que é muito grande
df_amostra.head() #.head mostra as primeiras linhas 
df_amostra.columns # mostra todas s colunas que tem na base de dados

Index(['Ano 1', 'Total Cen_00001', 'Unnamed: 2', '0,025138815'], dtype='str')

In [233]:
df_amostra.head(10).T

,0,1,2,3,4,5,6,7,8,9
Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1,Ano 1
Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001,Total Cen_00001
Unnamed: 2,BAL - Total do Ativo,BAL - Ativo Circulante,BAL - Disponível,BAL - Contas a Receber - SWAP,BAL - Contas a Receber - Partes Relacionadas,BAL - Contas a Receber - Clientes,BAL - Estoques Diversos,BAL - Outros Créditos,BAL - Realizável a Longo Prazo,BAL - At Fiscal Diferido
"0,025138815","10.631.127.075,26","1.795.720.872,18","1.205.264.965,52","95.680.421,92","584.661,47","453.870.957,15","86.620,79","40.233.245,33","639.023.858,23","-103.969.289,50"

In [234]:
df_amostra = pd.read_csv(
    caminho,
    sep=";",
    encoding="latin-1",
    header=2, # a linha 2 é o onde esta o nome das variaveis, então o pandas vai ler a partir dela
    nrows=1000
)

df_amostra.head()

,Ano 1,Total Cen_00001,BAL - Ativo Circulante,"1.795.720.872,18"
0,Ano 1,Total Cen_00001,BAL - Disponível,"1.205.264.965,52"
1,Ano 1,Total Cen_00001,BAL - Contas a Receber - SWAP,"95.680.421,92"
2,Ano 1,Total Cen_00001,BAL - Contas a Receber - Partes Relacionadas,"584.661,47"
3,Ano 1,Total Cen_00001,BAL - Contas a Receber - Clientes,"453.870.957,15"
4,Ano 1,Total Cen_00001,BAL - Estoques Diversos,"86.620,79"

In [235]:
with open(caminho, "r", encoding="latin-1") as arquivo:
    for i in range(10):
        print(i, repr(arquivo.readline())) # como resultado, vendo que a base não tem cabeçalho, então o pandas vai ler a partir da linha 2, que é onde estão os nomes das variáveis

0 'Ano 1;Total Cen_00001;;0,025138815\n'
1 'Ano 1;Total Cen_00001;BAL - Total do Ativo;10.631.127.075,26\n'
2 'Ano 1;Total Cen_00001;BAL - Ativo Circulante;1.795.720.872,18\n'
3 'Ano 1;Total Cen_00001;BAL - Disponível;1.205.264.965,52\n'
4 'Ano 1;Total Cen_00001;BAL - Contas a Receber - SWAP;95.680.421,92\n'
5 'Ano 1;Total Cen_00001;BAL - Contas a Receber - Partes Relacionadas;584.661,47\n'
6 'Ano 1;Total Cen_00001;BAL - Contas a Receber - Clientes;453.870.957,15\n'
7 'Ano 1;Total Cen_00001;BAL - Estoques Diversos;86.620,79\n'
8 'Ano 1;Total Cen_00001;BAL - Outros Créditos;40.233.245,33\n'
9 'Ano 1;Total Cen_00001;BAL - Realizável a Longo Prazo;639.023.858,23\n'

BASE COM CABEÇALHO: ANO | CENARIO | CONTA | VALOR

In [236]:
df_amostra = pd.read_csv(
    caminho,
    sep=";",
    encoding="latin-1",
    header=None,
    names=["Ano", "Cenario", "Conta", "Valor"], #mostra as as colunas que tem na base de dados
    nrows=1000
)

df_amostra.head(10)

,Ano,Cenario,Conta,Valor
0,Ano 1,Total Cen_00001,NaN,"0,025138815"
1,Ano 1,Total Cen_00001,BAL - Total do Ativo,"10.631.127.075,26"
2,Ano 1,Total Cen_00001,BAL - Ativo Circulante,"1.795.720.872,18"
3,Ano 1,Total Cen_00001,BAL - Disponível,"1.205.264.965,52"
4,Ano 1,Total Cen_00001,BAL - Contas a Receber - SWAP,"95.680.421,92"
5,Ano 1,Total Cen_00001,BAL - Contas a Receber - Partes Relacionadas,"584.661,47"
6,Ano 1,Total Cen_00001,BAL - Contas a Receber - Clientes,"453.870.957,15"
7,Ano 1,Total Cen_00001,BAL - Estoques Diversos,"86.620,79"
8,Ano 1,Total Cen_00001,BAL - Outros Créditos,"40.233.245,33"
9,Ano 1,Total Cen_00001,BAL - Realizável a Longo Prazo,"639.023.858,23"

In [237]:
df_amostra.info() #mostra informações sobre a base de dados, como o tipo de cada coluna e se tem valores nulos
#resultado: temos 1000 linhas e 4 colunas, sendo que a coluna Valor é do tipo float64, e as colunas Ano, Cenario e Conta são do tipo object. A coluna Valor tem 43 valores nulos, o que representa 4,3% dos dados. As outras colunas não tem valores nulos.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ano      1000 non-null   str
 1   Cenario  1000 non-null   str
 2   Conta    957 non-null    str
 3   Valor    1000 non-null   str
dtypes: str(4)
memory usage: 31.4 KB

In [238]:
df_amostra["Ano"].unique() #mostra os anos que tem na base de dados nas primeiras 1000 linhas

<StringArray>
['Ano 1']
Length: 1, dtype: str

In [239]:
df_amostra["Cenario"].unique() #mostra os cenários que tem na base de dados nas primeiras 1000 linhas
# resultado: dentro das primeiras 1000 linhas, temos 1 ano, 15 cenarios

<StringArray>
['Total Cen_00001', 'Total Cen_00002', 'Total Cen_00003', 'Total Cen_00004',
 'Total Cen_00005', 'Total Cen_00006', 'Total Cen_00007', 'Total Cen_00008',
 'Total Cen_00009', 'Total Cen_00010', 'Total Cen_00011', 'Total Cen_00012',
 'Total Cen_00013', 'Total Cen_00014', 'Total Cen_00015']
Length: 15, dtype: str

In [240]:
df_amostra["Cenario"].value_counts() #mostra a quantidade de vezes que cada cenário aparece na base de dados nas primeiras 1000 linhas
# resultado: no cenario 00001, tem 71 registros, no cenario 00002, tem 71 registros, e assim por diante. O cenario 00015 tem 70 registros, que so mostrou parcialmente aqui. Isso mostra que a base de dados está balanceada, ou seja, cada cenário tem aproximadamente o mesmo número de registros.

Cenario
Total Cen_00001    71
Total Cen_00002    71
Total Cen_00003    71
Total Cen_00004    71
Total Cen_00005    71
Total Cen_00006    71
Total Cen_00007    71
Total Cen_00008    71
Total Cen_00009    71
Total Cen_00010    71
Total Cen_00011    71
Total Cen_00012    71
Total Cen_00013    71
Total Cen_00014    71
Total Cen_00015     6
Name: count, dtype: int64

In [241]:
df_amostra[df_amostra["Cenario"] == "Total Cen_00001"]["Conta"].unique() #descobrindo quais contas aparecem dentro de uma cenário específico, no caso o cenario 00001. O resultado mostra que dentro do cenario 00001, temos 71 contas diferentes, que são as mesmas contas que aparecem nos outros cenarios, então a base de dados está balanceada.
#resultado: temos 71 contas diferentes, que são as mesmas contas que aparecem nos outros cenarios, então a base de dados está balanceada.

<StringArray>
[                                           nan,
                         'BAL - Total do Ativo',
                       'BAL - Ativo Circulante',
                             'BAL - Disponível',
                'BAL - Contas a Receber - SWAP',
 'BAL - Contas a Receber - Partes Relacionadas',
            'BAL - Contas a Receber - Clientes',
                      'BAL - Estoques Diversos',
                        'BAL - Outros Créditos',
               'BAL - Realizável a Longo Prazo',
                     'BAL - At Fiscal Diferido',
                   'BAL - Créditos Tributários',
                   'BAL - Outorga da Concessão',
                     'BAL - Outros Créditos LP',
                             'BAL - Permanente',
            'BAL - Investimentos - Imobilizado',
             'BAL - Investimentos - Intangível',
                               'BAL - Diferido',
                  'BAL - Depreciação Acumulada',
                  'BAL - Amortização Acumulada',
               'BAL - Amortização - Intangível',
                       'BAL - Total do Passivo',
                     'BAL - Passivo Circulante',
                            'BAL - Empréstimos',
     'BAL - Contas a Pagar - Parte Relacionada',
                           'BAL - Fornecedores',
        'BAL - Encargos Sociais e Trabalhistas',
                       'BAL - Tributos a pagar',
                               'BAL - Impostos',
      'BAL - Obrigações com o Poder Concedente',
                         'BAL - Outros Débitos',
                    'BAL - Provisão Manutenção',
                 'BAL - Exigível a Longo Prazo',
                                'BAL - Emprést',
               'BAL  - Prov para Contingências',
                             'BAL - Outros deb',
                    'BAL  - Patrimônio Líquido',
                        'BAL  - Capital Social',
                   'BAL  - Reservas de Capital',
                       'BAL  - Reservas Legais',
         'BAL  - Reserva de Retenção de Lucros',
                   'BAL  - Resultado Acumulado',
                  'BAL  - Resultado do Período',
                                'DRE - Receita',
                               'DRE - Tributos',
                                 'DRE - Custos',
              'DRE - Depreciação e Amortização',
                  'DRE - Resultado Operacional',
                   'DRE - Receitas Financeiras',
                   'DRE - Despesas Financeiras',
                   'DRE - Resultado Financeiro',
         'DRE - Outros Resultados Operacionais',
    'DRE - Resultado Antes do Imposto de Renda',
 'DRE - Imposto de Renda e Contribuição Social',
                      'DRE - Resultado Líquido',
    'DRE - Resultado Líquido após Equivalência',
                                 'DRE - EBITDA',
                          'FLU - Saldo Inicial',
                                'FLU - Receita',
                               'FLU - Tributos',
                                 'FLU - Custos',
                          'FLU - Investimentos',
                               'FLU - Entradas',
                   'FLU - Despesas Financeiras',
                   'FLU - Resultado Financeiro',
 'FLU - Imposto de Renda e Contribuição Social',
            'FLU - Distribuição para Acionista',
                       'FLU - Geração de Caixa',
                            'FLU - Saldo Final']
Length: 69, dtype: str

In [242]:
df_amostra["Conta"].dropna().str[:3].value_counts() #mostra a quantidade de vezes que cada conta aparece na base de dados nas primeiras 1000 linhas, considerando apenas os 3 primeiros caracteres da conta, que são os que indicam o tipo de conta. 
#df_amostra["Conta"] mostra só a coluna Conta
#.dropna() remove os valores nulos
#.str[:3] pega os 3 primeiros caracteres da conta

# O resultado mostra que temos 4 tipos de contas diferentes: 1. Receitas, 2. Custos, 3. Despesas e 4. Resultado.
# no info () vimos 957 valores preenchidos em conta, entao bateu. ou seja, temos 68 contas diferentes que aparece varias vezes uma vez em cada cenario

Conta
BAL    593
DRE    196
FLU    168
Name: count, dtype: int64

In [243]:
df_amostra[df_amostra["Cenario"] == "Total Cen_00001"].isna().sum() #diz quantos valores vazios tem em cada coluna de um cenario completo
#resultado, no cenario 00001, temos 0 valores nulos em Ano, Cenario e Conta, e 3 valores nulos em Valor. Isso mostra que a base de dados está balanceada, ou seja, cada cenário tem aproximadamente o mesmo número de registros.
df_amostra[
    (df_amostra["Cenario"] == "Total Cen_00001") &
    (df_amostra["Conta"].isna())
] #mostra os registros onde a conta é nula no cenario 00001
df_amostra["Cenario"].value_counts()

Cenario
Total Cen_00001    71
Total Cen_00002    71
Total Cen_00003    71
Total Cen_00004    71
Total Cen_00005    71
Total Cen_00006    71
Total Cen_00007    71
Total Cen_00008    71
Total Cen_00009    71
Total Cen_00010    71
Total Cen_00011    71
Total Cen_00012    71
Total Cen_00013    71
Total Cen_00014    71
Total Cen_00015     6
Name: count, dtype: int64

TOTAL DE CONTAS DIVIDIDAS: 68 CONTAS

In [244]:
df_amostra[
    (df_amostra["Cenario"] == "Total Cen_00001") &
    (df_amostra["Conta"].notna())
]["Conta"].str[:3].value_counts()

Conta
BAL    42
DRE    14
FLU    12
Name: count, dtype: int64

In [245]:
df_amostra[
    df_amostra["Cenario"] == "Total Cen_00002"
]["Conta"].dropna().nunique()
#temos 71 registros por cenario, 68 contas e 3 parametros separando BAL, DRE e FLU

68

In [246]:
contas_cenario_1 = set(
    df_amostra[
        df_amostra["Cenario"] == "Total Cen_00001"
    ]["Conta"].dropna()
) #nao aparece nada, é so pra guardar essa estrutura como amostra, para depois comparar com os outros cenarios e ver se tem alguma conta que aparece em um cenario e não aparece em outro

VALOR DO ATIVO TOTAL EM CADA CENARIO

In [247]:
#VALOR DO ATIVO TOTAL EM CADA CENARIO
df_amostra[
    df_amostra["Conta"] == "BAL - Total do Ativo"
][["Cenario", "Valor"]] #mostra o valor do ativo total em cada cenario, para ver se tem alguma diferença entre os cenarios
#resultado: O Total do Ativo muda entre os cenários, mas não muda de forma absurda:
#Cenário 1: R$ 10,631 bi
#Menor na amostra: Cenário 5 → R$ 10,602 bi
#Maior: Cenário 13 → R$ 10,649 bi
#Cenário 15 → R$ 10,628 bi

             Cenario              Valor
1    Total Cen_00001  10.631.127.075,26
72   Total Cen_00002  10.623.913.756,08
143  Total Cen_00003  10.623.167.968,07
214  Total Cen_00004  10.623.286.492,97
285  Total Cen_00005  10.601.794.070,01
356  Total Cen_00006  10.615.960.661,01
427  Total Cen_00007  10.606.251.258,79
498  Total Cen_00008  10.615.012.125,10
569  Total Cen_00009  10.617.439.213,50
640  Total Cen_00010  10.616.828.667,09
711  Total Cen_00011  10.611.376.775,79
782  Total Cen_00012  10.643.452.351,17
853  Total Cen_00013  10.649.142.827,96
924  Total Cen_00014  10.615.117.816,07
995  Total Cen_00015  10.627.703.778,67

VALOR DA RECEITA EM CADA CENARIO

In [248]:
#VALOR DA RECEITA EM CADA CENARIO
df_amostra[
    df_amostra["Conta"] == "DRE - Receita"
][["Cenario", "Valor"]] #mostra o valor da receita em cada cenario, para ver se tem alguma diferença entre os cenarios
#resultado: ela fica em torno de R$ 6,66–6,73 bilhões, então existe uma variação relativamente pequena, mas real, entre as simulações.

             Cenario             Valor
44   Total Cen_00001  6.722.729.306,39
115  Total Cen_00002  6.703.607.585,78
186  Total Cen_00003  6.676.361.231,67
257  Total Cen_00004  6.672.623.329,65
328  Total Cen_00005  6.660.652.567,40
399  Total Cen_00006  6.672.505.598,62
470  Total Cen_00007  6.668.819.159,60
541  Total Cen_00008  6.668.751.986,23
612  Total Cen_00009  6.664.961.468,41
683  Total Cen_00010  6.658.854.732,84
754  Total Cen_00011  6.657.545.825,55
825  Total Cen_00012  6.711.229.599,43
896  Total Cen_00013  6.730.501.277,24
967  Total Cen_00014  6.699.737.545,12

VERIFICANDO SE RECEITA E TOTAL DO ATIVO SÃO VARIANTES COM CORRELAÇÃO

In [ ]:
df_amostra[
    df_amostra["Conta"].isin([
        "BAL - Total do Ativo",
        "DRE - Receita"
    ])
][["Cenario", "Conta", "Valor"]] #mostra o valor do ativo total e da receita em cada cenario, para ver se tem alguma diferença entre os cenarios

             Cenario                 Conta              Valor
1    Total Cen_00001  BAL - Total do Ativo  10.631.127.075,26
44   Total Cen_00001         DRE - Receita   6.722.729.306,39
72   Total Cen_00002  BAL - Total do Ativo  10.623.913.756,08
115  Total Cen_00002         DRE - Receita   6.703.607.585,78
143  Total Cen_00003  BAL - Total do Ativo  10.623.167.968,07
186  Total Cen_00003         DRE - Receita   6.676.361.231,67
214  Total Cen_00004  BAL - Total do Ativo  10.623.286.492,97
257  Total Cen_00004         DRE - Receita   6.672.623.329,65
285  Total Cen_00005  BAL - Total do Ativo  10.601.794.070,01
328  Total Cen_00005         DRE - Receita   6.660.652.567,40
356  Total Cen_00006  BAL - Total do Ativo  10.615.960.661,01
399  Total Cen_00006         DRE - Receita   6.672.505.598,62
427  Total Cen_00007  BAL - Total do Ativo  10.606.251.258,79
470  Total Cen_00007         DRE - Receita   6.668.819.159,60
498  Total Cen_00008  BAL - Total do Ativo  10.615.012.125,10
541  Total Cen_00008         DRE - Receita   6.668.751.986,23
569  Total Cen_00009  BAL - Total do Ativo  10.617.439.213,50
612  Total Cen_00009         DRE - Receita   6.664.961.468,41
640  Total Cen_00010  BAL - Total do Ativo  10.616.828.667,09
683  Total Cen_00010         DRE - Receita   6.658.854.732,84
711  Total Cen_00011  BAL - Total do Ativo  10.611.376.775,79
754  Total Cen_00011         DRE - Receita   6.657.545.825,55
782  Total Cen_00012  BAL - Total do Ativo  10.643.452.351,17
825  Total Cen_00012         DRE - Receita   6.711.229.599,43
853  Total Cen_00013  BAL - Total do Ativo  10.649.142.827,96
896  Total Cen_00013         DRE - Receita   6.730.501.277,24
924  Total Cen_00014  BAL - Total do Ativo  10.615.117.816,07
967  Total Cen_00014         DRE - Receita   6.699.737.545,12
995  Total Cen_00015  BAL - Total do Ativo  10.627.703.778,67